"Module: twinkle":
- changed-files:
  - any-glob-to-any-file:
    - twinkle.js
    - twinkle.css
    - twinkle-pagestyles.css
"Module: morebits":
- changed-files:
  - any-glob-to-any-file:
    - morebits.js
    - morebits.css
"Module: arv":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklearv.js
"Module: batch":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklebatchdelete.js
    - modules/twinklebatchundelete.js
    - modules/twinklebatchprotect.js
    - modules/twinkledeprod.js
"Module: block":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinkleblock.js
"Module: config":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinkleconfig.js
"Module: diff":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklediff.js
"Module: fluff":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklefluff.js
"Module: prod":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinkleprod.js
"Module: protect":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinkleprotect.js
"Module: speedy":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklespeedy.js
    - modules/twinkleimage.js
"Module: tag":
- changed-files:
  - any-glob-to-any-file:
    - modules/friendlytag.js
"Module: talkback":
- changed-files:
  - any-glob-to-any-file:
    - modules/friendlytalkback.js
"Module: unlink":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinkleunlink.js
"Module: warn":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklewarn.js
"Module: welcome":
- changed-files:
  - any-glob-to-any-file:
    - modules/friendlywelcome.js
"Module: xfd":
- changed-files:
  - any-glob-to-any-file:
    - modules/twinklexfd.js
Tests:
- changed-files:
  - any-glob-to-any-file:
    - tests/*
    - scripts/patch-test.js
    - scripts/server.js
    - ".github/*"
Docs:
- changed-files:
  - any-glob-to-any-file:
    - "*.md"
Gadget:
- changed-files:
  - any-glob-to-any-file:
    - gadget.txt
dependencies:
- changed-files:
  - any-glob-to-any-file:
    - package.json
    - package-lock.json
